import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { SelectTokenProvider } from "./context/SelectTokenProvider";
import { TokenBalanceProvider } from "./context/TokenBalanceProvider";
import { AnchorProvider } from "./context/AnchorProvider";
import RPCProvider from "./context/RPCProvider";

const space_grotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="theme1">
      <body className={space_grotesk.className}>
        {
          <RPCProvider>
            <AnchorProvider>
              <SelectTokenProvider>
                <TokenBalanceProvider>{children}</TokenBalanceProvider>
              </SelectTokenProvider>
            </AnchorProvider>
          </RPCProvider>
        }
      </body>
    </html>
  );
}
